name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-22.04, windows-2022]

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4

            -   uses: Jimver/cuda-toolkit@v0.2.19
                id: cuda-toolkit
                with:
                    cuda: '12.6.2'
                    method: 'local'

            -   name: Check CUDA
                run: |
                    echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
                    echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
                    nvcc -V

            -   name: Build
                run: make build

            -   name: Test
                run: |
                    make run
                    make test
