name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os:
                    - ubuntu-20.04
                    - windows-2019
        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4

            -   uses: Jimver/cuda-toolkit@v0.2.17
                id: cuda-toolkit
                with:
                    log-file-suffix: ${{ matrix.os }}.txt

            -   name: Build
                run: make build

            -   name: Test
                run: |
                    make run
                    make test
